// Purchase notifications for quantum-key pages - separated by language/country

// Portuguese - Lusophone countries (50 names)
export const brazilianPurchaseNotifications = [
  { name: "Maria Silva", location: "São Paulo, Brasil" },
  { name: "João Santos", location: "Rio de Janeiro, Brasil" },
  { name: "Ana Costa", location: "Lisboa, Portugal" },
  { name: "Pedro Oliveira", location: "Belo Horizonte, Brasil" },
  { name: "Carla Souza", location: "Porto, Portugal" },
  { name: "Lucas Ferreira", location: "Brasília, Brasil" },
  { name: "Juliana Lima", location: "Salvador, Brasil" },
  { name: "Roberto Alves", location: "Luanda, Angola" },
  { name: "Patricia Ribeiro", location: "Recife, Brasil" },
  { name: "Fernando Martins", location: "Maputo, Moçambique" },
  { name: "Gabriela Mendes", location: "Goiânia, Brasil" },
  { name: "Rafael Rodrigues", location: "Campinas, Brasil" },
  { name: "Camila Almeida", location: "Praia, Cabo Verde" },
  { name: "Diego Pereira", location: "Belém, Brasil" },
  { name: "Beatriz Cardoso", location: "Coimbra, Portugal" },
  { name: "Thiago Barbosa", location: "Vitória, Brasil" },
  { name: "Amanda Teixeira", location: "Natal, Brasil" },
  { name: "Marcelo Gomes", location: "Bissau, Guiné-Bissau" },
  { name: "Renata Castro", location: "Aracaju, Brasil" },
  { name: "Bruno Araújo", location: "Maceió, Brasil" },
  { name: "Vanessa Dias", location: "São Tomé, São Tomé e Príncipe" },
  { name: "André Moreira", location: "Campo Grande, Brasil" },
  { name: "Larissa Nunes", location: "Teresina, Brasil" },
  { name: "Ricardo Monteiro", location: "Dili, Timor-Leste" },
  { name: "Priscila Rocha", location: "Londrina, Brasil" },
  { name: "Carlos Mendes", location: "Braga, Portugal" },
  { name: "Fernanda Costa", location: "Niterói, Brasil" },
  { name: "Gustavo Silva", location: "Benguela, Angola" },
  { name: "Mariana Pereira", location: "Uberlândia, Brasil" },
  { name: "Eduardo Barbosa", location: "Faro, Portugal" },
  { name: "Aline Teixeira", location: "Beira, Moçambique" },
  { name: "Rodrigo Martins", location: "Contagem, Brasil" },
  { name: "Tatiana Rocha", location: "Mindelo, Cabo Verde" },
  { name: "Felipe Araújo", location: "Caxias do Sul, Brasil" },
  { name: "Daniela Gomes", location: "Setúbal, Portugal" },
  { name: "Vinicius Lima", location: "Piracicaba, Brasil" },
  { name: "Renata Dias", location: "Huambo, Angola" },
  { name: "Marcos Ferreira", location: "Caruaru, Brasil" },
  { name: "Juliana Castro", location: "Nampula, Moçambique" },
  { name: "Leonardo Nunes", location: "Palmas, Brasil" },
  { name: "Carolina Moreira", location: "Funchal, Portugal" },
  { name: "Alexandre Pinto", location: "Montes Claros, Brasil" },
  { name: "Isabela Monteiro", location: "Lobito, Angola" },
  { name: "Fabio Cardoso", location: "Blumenau, Brasil" },
  { name: "Claudia Santana", location: "Quelimane, Moçambique" },
  { name: "Henrique Campos", location: "Juiz de Fora, Brasil" },
  { name: "Paula Freitas", location: "Évora, Portugal" },
  { name: "Sergio Batista", location: "Santa Maria, Cabo Verde" },
  { name: "Viviane Moura", location: "Petrolina, Brasil" },
  { name: "Douglas Correia", location: "Malabo, Guiné Equatorial" },
];

// Brazil only - for physical book page (50 names)
export const brazilOnlyPurchaseNotifications = [
  { name: "Maria Silva", location: "São Paulo, SP" },
  { name: "João Santos", location: "Rio de Janeiro, RJ" },
  { name: "Pedro Oliveira", location: "Belo Horizonte, MG" },
  { name: "Lucas Ferreira", location: "Brasília, DF" },
  { name: "Juliana Lima", location: "Salvador, BA" },
  { name: "Patricia Ribeiro", location: "Recife, PE" },
  { name: "Gabriela Mendes", location: "Goiânia, GO" },
  { name: "Rafael Rodrigues", location: "Campinas, SP" },
  { name: "Diego Pereira", location: "Belém, PA" },
  { name: "Thiago Barbosa", location: "Vitória, ES" },
  { name: "Amanda Teixeira", location: "Natal, RN" },
  { name: "Renata Castro", location: "Aracaju, SE" },
  { name: "Bruno Araújo", location: "Maceió, AL" },
  { name: "André Moreira", location: "Campo Grande, MS" },
  { name: "Larissa Nunes", location: "Teresina, PI" },
  { name: "Priscila Rocha", location: "Londrina, PR" },
  { name: "Fernanda Costa", location: "Niterói, RJ" },
  { name: "Mariana Pereira", location: "Uberlândia, MG" },
  { name: "Rodrigo Martins", location: "Contagem, MG" },
  { name: "Felipe Araújo", location: "Caxias do Sul, RS" },
  { name: "Vinicius Lima", location: "Piracicaba, SP" },
  { name: "Marcos Ferreira", location: "Caruaru, PE" },
  { name: "Leonardo Nunes", location: "Palmas, TO" },
  { name: "Alexandre Pinto", location: "Montes Claros, MG" },
  { name: "Fabio Cardoso", location: "Blumenau, SC" },
  { name: "Henrique Campos", location: "Juiz de Fora, MG" },
  { name: "Viviane Moura", location: "Petrolina, PE" },
  { name: "Carla Souza", location: "Porto Alegre, RS" },
  { name: "Camila Almeida", location: "Florianópolis, SC" },
  { name: "Beatriz Cardoso", location: "São Luís, MA" },
  { name: "Vanessa Dias", location: "Cuiabá, MT" },
  { name: "Ricardo Monteiro", location: "Ribeirão Preto, SP" },
  { name: "Carlos Mendes", location: "Santos, SP" },
  { name: "Gustavo Silva", location: "Guarulhos, SP" },
  { name: "Eduardo Barbosa", location: "Sorocaba, SP" },
  { name: "Aline Teixeira", location: "São José dos Campos, SP" },
  { name: "Tatiana Rocha", location: "Joinville, SC" },
  { name: "Daniela Gomes", location: "Maringá, PR" },
  { name: "Renata Dias", location: "Jundiaí, SP" },
  { name: "Juliana Castro", location: "Imperatriz, MA" },
  { name: "Carolina Moreira", location: "Bauru, SP" },
  { name: "Isabela Monteiro", location: "Franca, SP" },
  { name: "Claudia Santana", location: "Pelotas, RS" },
  { name: "Paula Freitas", location: "Aparecida de Goiânia, GO" },
  { name: "Sergio Batista", location: "Anápolis, GO" },
  { name: "Douglas Correia", location: "Chapecó, SC" },
  { name: "Roberto Alves", location: "Fortaleza, CE" },
  { name: "Fernando Martins", location: "Manaus, AM" },
  { name: "Marcelo Gomes", location: "João Pessoa, PB" },
  { name: "Ana Costa", location: "Curitiba, PR" },
];

// English - Anglophone countries (50 names)
export const americanPurchaseNotifications = [
  { name: "John Smith", location: "New York, United States" },
  { name: "Sarah Johnson", location: "London, United Kingdom" },
  { name: "Michael Brown", location: "Toronto, Canada" },
  { name: "Emily Davis", location: "Sydney, Australia" },
  { name: "David Wilson", location: "Dublin, Ireland" },
  { name: "Jessica Martinez", location: "Los Angeles, United States" },
  { name: "James Anderson", location: "Lagos, Nigeria" },
  { name: "Jennifer Taylor", location: "Auckland, New Zealand" },
  { name: "Robert Thomas", location: "Chicago, United States" },
  { name: "Linda Garcia", location: "Cape Town, South Africa" },
  { name: "Christopher Lee", location: "Manchester, United Kingdom" },
  { name: "Amanda White", location: "Vancouver, Canada" },
  { name: "Daniel Harris", location: "Melbourne, Australia" },
  { name: "Patricia Clark", location: "Houston, United States" },
  { name: "Matthew Lewis", location: "Nairobi, Kenya" },
  { name: "Elizabeth Walker", location: "Kingston, Jamaica" },
  { name: "Andrew Hall", location: "Mumbai, India" },
  { name: "Sophia Allen", location: "Boston, United States" },
  { name: "Ryan Young", location: "Accra, Ghana" },
  { name: "Olivia King", location: "Singapore, Singapore" },
  { name: "Kevin Wright", location: "Edinburgh, United Kingdom" },
  { name: "Michelle Green", location: "Miami, United States" },
  { name: "Brandon Scott", location: "Kampala, Uganda" },
  { name: "Ashley Baker", location: "Perth, Australia" },
  { name: "Justin Adams", location: "Manila, Philippines" },
  { name: "Rachel Nelson", location: "Johannesburg, South Africa" },
  { name: "Tyler Carter", location: "Montreal, Canada" },
  { name: "Megan Hill", location: "Nairobi, Kenya" },
  { name: "Joshua Mitchell", location: "Seattle, United States" },
  { name: "Samantha Roberts", location: "Bridgetown, Barbados" },
  { name: "Nicholas Turner", location: "Karachi, Pakistan" },
  { name: "Lauren Phillips", location: "San Francisco, United States" },
  { name: "Nathan Campbell", location: "Colombo, Sri Lanka" },
  { name: "Victoria Parker", location: "Belfast, United Kingdom" },
  { name: "Jonathan Evans", location: "Kuala Lumpur, Malaysia" },
  { name: "Hannah Edwards", location: "Atlanta, United States" },
  { name: "Zachary Collins", location: "Lusaka, Zambia" },
  { name: "Madison Stewart", location: "Brisbane, Australia" },
  { name: "Aaron Morris", location: "Nassau, Bahamas" },
  { name: "Emma Rogers", location: "Port of Spain, Trinidad and Tobago" },
  { name: "Jacob Reed", location: "Denver, United States" },
  { name: "Grace Cook", location: "Harare, Zimbabwe" },
  { name: "Ethan Morgan", location: "Glasgow, United Kingdom" },
  { name: "Chloe Bell", location: "Suva, Fiji" },
  { name: "Alexander Murphy", location: "Lagos, Nigeria" },
  { name: "Abigail Bailey", location: "Calgary, Canada" },
  { name: "William Rivera", location: "Gaborone, Botswana" },
  { name: "Natalie Cooper", location: "San Diego, United States" },
  { name: "Benjamin Richardson", location: "Windhoek, Namibia" },
  { name: "Lily Cox", location: "Freetown, Sierra Leone" },
];

// Spanish - Hispanic countries (50 names)
export const spanishPurchaseNotifications = [
  { name: "Carlos García", location: "Madrid, España" },
  { name: "María López", location: "Ciudad de México, México" },
  { name: "José Martínez", location: "Buenos Aires, Argentina" },
  { name: "Ana Rodríguez", location: "Barcelona, España" },
  { name: "Francisco Pérez", location: "Bogotá, Colombia" },
  { name: "Laura Sánchez", location: "Lima, Perú" },
  { name: "Antonio Ramírez", location: "Santiago, Chile" },
  { name: "Carmen Torres", location: "Valencia, España" },
  { name: "Juan Flores", location: "Caracas, Venezuela" },
  { name: "Isabel Gómez", location: "Quito, Ecuador" },
  { name: "Pedro Navarro", location: "Guadalajara, México" },
  { name: "Lucía Ruiz", location: "Sevilla, España" },
  { name: "Miguel Díaz", location: "Montevideo, Uruguay" },
  { name: "Elena Moreno", location: "La Paz, Bolivia" },
  { name: "Javier Jiménez", location: "Asunción, Paraguay" },
  { name: "Sara Hernández", location: "Córdoba, Argentina" },
  { name: "David Álvarez", location: "Medellín, Colombia" },
  { name: "Cristina Romero", location: "Monterrey, México" },
  { name: "Raúl Castro", location: "La Habana, Cuba" },
  { name: "Patricia Ortiz", location: "Santo Domingo, República Dominicana" },
  { name: "Alberto Rubio", location: "San Juan, Puerto Rico" },
  { name: "Marta Serrano", location: "Málaga, España" },
  { name: "Sergio Blanco", location: "Ciudad de Guatemala, Guatemala" },
  { name: "Natalia Suárez", location: "Tegucigalpa, Honduras" },
  { name: "Pablo Vega", location: "San Salvador, El Salvador" },
  { name: "Andrea Molina", location: "Managua, Nicaragua" },
  { name: "Daniel Morales", location: "San José, Costa Rica" },
  { name: "Silvia Gil", location: "Ciudad de Panamá, Panamá" },
  { name: "Roberto Núñez", location: "Bilbao, España" },
  { name: "Beatriz Iglesias", location: "Rosario, Argentina" },
  { name: "Víctor Guerrero", location: "Puebla, México" },
  { name: "Adriana Prieto", location: "Cali, Colombia" },
  { name: "Manuel Delgado", location: "Valparaíso, Chile" },
  { name: "Rocío Medina", location: "Arequipa, Perú" },
  { name: "Jorge Cortés", location: "Guayaquil, Ecuador" },
  { name: "Lorena Cabrera", location: "Zaragoza, España" },
  { name: "Ángel Lozano", location: "Valencia, Venezuela" },
  { name: "Mónica Garrido", location: "Santa Cruz, Bolivia" },
  { name: "Fernando Méndez", location: "Tijuana, México" },
  { name: "Susana Vargas", location: "Granada, España" },
  { name: "Alejandro Santos", location: "Cuenca, Ecuador" },
  { name: "Verónica Ramos", location: "Alicante, España" },
  { name: "Rubén Domínguez", location: "Barranquilla, Colombia" },
  { name: "Pilar Herrera", location: "León, México" },
  { name: "Iván Aguilar", location: "Mar del Plata, Argentina" },
  { name: "Nuria Parra", location: "Pamplona, España" },
  { name: "Óscar Vázquez", location: "Cusco, Perú" },
  { name: "Teresa Márquez", location: "Viña del Mar, Chile" },
  { name: "Diego Soto", location: "Punta del Este, Uruguay" },
  { name: "Amparo Fernández", location: "Malabo, Guinea Ecuatorial" },
];
