// Purchase notifications for quantum-key pages - separated by language/country

// Portuguese - Lusophone countries (50 names)
export const brazilianPurchaseNotifications = [
  { name: "Maria Silva", location: "São Paulo, Brasil" },
  { name: "João Santos", location: "Rio de Janeiro, Brasil" },
  { name: "Ana Costa", location: "Lisboa, Portugal" },
  { name: "Pedro Oliveira", location: "Belo Horizonte, Brasil" },
  { name: "Carla Souza", location: "Porto, Portugal" },
  { name: "Lucas Ferreira", location: "Brasília, Brasil" },
  { name: "Juliana Lima", location: "Salvador, Brasil" },
  { name: "Roberto Alves", location: "Luanda, Angola" },
  { name: "Patricia Ribeiro", location: "Recife, Brasil" },
  { name: "Fernando Martins", location: "Maputo, Moçambique" },
  { name: "Gabriela Mendes", location: "Goiânia, Brasil" },
  { name: "Rafael Rodrigues", location: "Campinas, Brasil" },
  { name: "Camila Almeida", location: "Praia, Cabo Verde" },
  { name: "Diego Pereira", location: "Belém, Brasil" },
  { name: "Beatriz Cardoso", location: "Coimbra, Portugal" },
  { name: "Thiago Barbosa", location: "Vitória, Brasil" },
  { name: "Amanda Teixeira", location: "Natal, Brasil" },
  { name: "Marcelo Gomes", location: "Bissau, Guiné-Bissau" },
  { name: "Renata Castro", location: "Aracaju, Brasil" },
  { name: "Bruno Araújo", location: "Maceió, Brasil" },
  { name: "Vanessa Dias", location: "São Tomé, São Tomé e Príncipe" },
  { name: "André Moreira", location: "Campo Grande, Brasil" },
  { name: "Larissa Nunes", location: "Teresina, Brasil" },
  { name: "Ricardo Monteiro", location: "Dili, Timor-Leste" },
  { name: "Priscila Rocha", location: "Londrina, Brasil" },
  { name: "Carlos Mendes", location: "Braga, Portugal" },
  { name: "Fernanda Costa", location: "Niterói, Brasil" },
  { name: "Gustavo Silva", location: "Benguela, Angola" },
  { name: "Mariana Pereira", location: "Uberlândia, Brasil" },
  { name: "Eduardo Barbosa", location: "Faro, Portugal" },
  { name: "Aline Teixeira", location: "Beira, Moçambique" },
  { name: "Rodrigo Martins", location: "Contagem, Brasil" },
  { name: "Tatiana Rocha", location: "Mindelo, Cabo Verde" },
  { name: "Felipe Araújo", location: "Caxias do Sul, Brasil" },
  { name: "Daniela Gomes", location: "Setúbal, Portugal" },
  { name: "Vinicius Lima", location: "Piracicaba, Brasil" },
  { name: "Renata Dias", location: "Huambo, Angola" },
  { name: "Marcos Ferreira", location: "Caruaru, Brasil" },
  { name: "Juliana Castro", location: "Nampula, Moçambique" },
  { name: "Leonardo Nunes", location: "Palmas, Brasil" },
  { name: "Carolina Moreira", location: "Funchal, Portugal" },
  { name: "Alexandre Pinto", location: "Montes Claros, Brasil" },
  { name: "Isabela Monteiro", location: "Lobito, Angola" },
  { name: "Fabio Cardoso", location: "Blumenau, Brasil" },
  { name: "Claudia Santana", location: "Quelimane, Moçambique" },
  { name: "Henrique Campos", location: "Juiz de Fora, Brasil" },
  { name: "Paula Freitas", location: "Évora, Portugal" },
  { name: "Sergio Batista", location: "Santa Maria, Cabo Verde" },
  { name: "Viviane Moura", location: "Petrolina, Brasil" },
  { name: "Douglas Correia", location: "Malabo, Guiné Equatorial" },
];

// English - Anglophone countries (50 names)
export const americanPurchaseNotifications = [
  { name: "John Smith", location: "New York, Estados Unidos" },
  { name: "Sarah Johnson", location: "Londres, Reino Unido" },
  { name: "Michael Brown", location: "Toronto, Canadá" },
  { name: "Emily Davis", location: "Sydney, Austrália" },
  { name: "David Wilson", location: "Dublin, Irlanda" },
  { name: "Jessica Martinez", location: "Los Angeles, Estados Unidos" },
  { name: "James Anderson", location: "Lagos, Nigéria" },
  { name: "Jennifer Taylor", location: "Auckland, Nova Zelândia" },
  { name: "Robert Thomas", location: "Chicago, Estados Unidos" },
  { name: "Linda Garcia", location: "Cape Town, África do Sul" },
  { name: "Christopher Lee", location: "Manchester, Reino Unido" },
  { name: "Amanda White", location: "Vancouver, Canadá" },
  { name: "Daniel Harris", location: "Melbourne, Austrália" },
  { name: "Patricia Clark", location: "Houston, Estados Unidos" },
  { name: "Matthew Lewis", location: "Nairobi, Quênia" },
  { name: "Elizabeth Walker", location: "Kingston, Jamaica" },
  { name: "Andrew Hall", location: "Mumbai, Índia" },
  { name: "Sophia Allen", location: "Boston, Estados Unidos" },
  { name: "Ryan Young", location: "Accra, Gana" },
  { name: "Olivia King", location: "Singapore, Singapura" },
  { name: "Kevin Wright", location: "Edinburgh, Reino Unido" },
  { name: "Michelle Green", location: "Miami, Estados Unidos" },
  { name: "Brandon Scott", location: "Kampala, Uganda" },
  { name: "Ashley Baker", location: "Perth, Austrália" },
  { name: "Justin Adams", location: "Manila, Filipinas" },
  { name: "Rachel Nelson", location: "Johannesburg, África do Sul" },
  { name: "Tyler Carter", location: "Montreal, Canadá" },
  { name: "Megan Hill", location: "Nairobi, Quênia" },
  { name: "Joshua Mitchell", location: "Seattle, Estados Unidos" },
  { name: "Samantha Roberts", location: "Bridgetown, Barbados" },
  { name: "Nicholas Turner", location: "Karachi, Paquistão" },
  { name: "Lauren Phillips", location: "San Francisco, Estados Unidos" },
  { name: "Nathan Campbell", location: "Colombo, Sri Lanka" },
  { name: "Victoria Parker", location: "Belfast, Reino Unido" },
  { name: "Jonathan Evans", location: "Kuala Lumpur, Malásia" },
  { name: "Hannah Edwards", location: "Atlanta, Estados Unidos" },
  { name: "Zachary Collins", location: "Lusaka, Zâmbia" },
  { name: "Madison Stewart", location: "Brisbane, Austrália" },
  { name: "Aaron Morris", location: "Nassau, Bahamas" },
  { name: "Emma Rogers", location: "Port of Spain, Trinidad e Tobago" },
  { name: "Jacob Reed", location: "Denver, Estados Unidos" },
  { name: "Grace Cook", location: "Harare, Zimbábue" },
  { name: "Ethan Morgan", location: "Glasgow, Reino Unido" },
  { name: "Chloe Bell", location: "Suva, Fiji" },
  { name: "Alexander Murphy", location: "Lagos, Nigéria" },
  { name: "Abigail Bailey", location: "Calgary, Canadá" },
  { name: "William Rivera", location: "Gaborone, Botsuana" },
  { name: "Natalie Cooper", location: "San Diego, Estados Unidos" },
  { name: "Benjamin Richardson", location: "Windhoek, Namíbia" },
  { name: "Lily Cox", location: "Freetown, Serra Leoa" },
];

// Spanish - Hispanic countries (50 names)
export const spanishPurchaseNotifications = [
  { name: "Carlos García", location: "Madrid, Espanha" },
  { name: "María López", location: "Cidade do México, México" },
  { name: "José Martínez", location: "Buenos Aires, Argentina" },
  { name: "Ana Rodríguez", location: "Barcelona, Espanha" },
  { name: "Francisco Pérez", location: "Bogotá, Colômbia" },
  { name: "Laura Sánchez", location: "Lima, Peru" },
  { name: "Antonio Ramírez", location: "Santiago, Chile" },
  { name: "Carmen Torres", location: "Valencia, Espanha" },
  { name: "Juan Flores", location: "Caracas, Venezuela" },
  { name: "Isabel Gómez", location: "Quito, Equador" },
  { name: "Pedro Navarro", location: "Guadalajara, México" },
  { name: "Lucía Ruiz", location: "Sevilla, Espanha" },
  { name: "Miguel Díaz", location: "Montevideo, Uruguai" },
  { name: "Elena Moreno", location: "La Paz, Bolívia" },
  { name: "Javier Jiménez", location: "Asunción, Paraguai" },
  { name: "Sara Hernández", location: "Córdoba, Argentina" },
  { name: "David Álvarez", location: "Medellín, Colômbia" },
  { name: "Cristina Romero", location: "Monterrey, México" },
  { name: "Raúl Castro", location: "Havana, Cuba" },
  { name: "Patricia Ortiz", location: "Santo Domingo, República Dominicana" },
  { name: "Alberto Rubio", location: "San Juan, Porto Rico" },
  { name: "Marta Serrano", location: "Málaga, Espanha" },
  { name: "Sergio Blanco", location: "Guatemala City, Guatemala" },
  { name: "Natalia Suárez", location: "Tegucigalpa, Honduras" },
  { name: "Pablo Vega", location: "San Salvador, El Salvador" },
  { name: "Andrea Molina", location: "Managua, Nicarágua" },
  { name: "Daniel Morales", location: "San José, Costa Rica" },
  { name: "Silvia Gil", location: "Cidade do Panamá, Panamá" },
  { name: "Roberto Núñez", location: "Bilbao, Espanha" },
  { name: "Beatriz Iglesias", location: "Rosario, Argentina" },
  { name: "Víctor Guerrero", location: "Puebla, México" },
  { name: "Adriana Prieto", location: "Cali, Colômbia" },
  { name: "Manuel Delgado", location: "Valparaíso, Chile" },
  { name: "Rocío Medina", location: "Arequipa, Peru" },
  { name: "Jorge Cortés", location: "Guayaquil, Equador" },
  { name: "Lorena Cabrera", location: "Zaragoza, Espanha" },
  { name: "Ángel Lozano", location: "Valencia, Venezuela" },
  { name: "Mónica Garrido", location: "Santa Cruz, Bolívia" },
  { name: "Fernando Méndez", location: "Tijuana, México" },
  { name: "Susana Vargas", location: "Granada, Espanha" },
  { name: "Alejandro Santos", location: "Cuenca, Equador" },
  { name: "Verónica Ramos", location: "Alicante, Espanha" },
  { name: "Rubén Domínguez", location: "Barranquilla, Colômbia" },
  { name: "Pilar Herrera", location: "León, México" },
  { name: "Iván Aguilar", location: "Mar del Plata, Argentina" },
  { name: "Nuria Parra", location: "Pamplona, Espanha" },
  { name: "Óscar Vázquez", location: "Cusco, Peru" },
  { name: "Teresa Márquez", location: "Viña del Mar, Chile" },
  { name: "Diego Soto", location: "Punta del Este, Uruguai" },
  { name: "Amparo Fernández", location: "Malabo, Guiné Equatorial" },
];
